global using Unity;
global using UnityEngine;
global using UnityEngine.AddressableAssets;
global using Sandswept.Utils;
global using R2API;
global using Random = UnityEngine.Random;
global using RoR2;
global using RoR2.Skills;
global using RoR2.Projectile;
global using EntityStates;
global using SearchableAttribute = HG.Reflection.SearchableAttribute;
global using System.Collections.Generic;
global using System;
global using Object = UnityEngine.Object;
global using UnityEngine.Networking;
global using BepInEx.Configuration;
global using static R2API.RecalculateStatsAPI;
global using Paths = Sandswept.Utils.Assets;
global using static R2API.DirectorAPI;
global using Stage = R2API.DirectorAPI.Stage;